### ISSUE TITLE
2016-03-16 Updates to REP wireframes

### ISSUE THREAD

**Issue by vdilawri** [hres/wireframes#11]
Hi Chi,  Below are the update requests from client on REP mock-ups that we discussed this morning.  
Thanks again for all the effort!
Vinay

=======

1.	Step 3 (CO, DO, RA templates):
a.	 Change the bottom button text from : ‘Generate XML’ to ‘Generate DRAFT XML’.  
     i.	Also, when button is clicked, a pop-up box with the following text ‘Submit to Health Canada’  [note: this text is placeholder for additional help  text to follow].

2.	Step 3 (RT template): 
a.	Change the bottom button text from: ‘Generate XML’ to ‘Generate FINAL XML’
      i.	Also, when button is clicked, a pop-up box with the following text ‘Submit to Health Canada’  [note: this text is placeholder for additional help  text to follow].

3.	Step 3 (CO, DO, RA, RT Templates):
a.	 Need to add ‘Same-as Main Contact (From Step 1a) ’ YES-NO buttons (similar to CO step 2 template).  
     i.	When YES selected, the Main Contact data is pre-populated into the fields and visible to user (if possible).
     ii.	When NO selected, the data fields appear as blank

4.	Step 2 (CO Template):
a.	 The ‘Company Representative Information’ data should also have a ‘YES-NO’ button, with the question: Same as Main Contact information from Step 1a?.
b.	 Update the label for the remaining Company representative question with “ Same as Main Contact information from Step 1a?’

5.	Step 2 (RT Template): Several updates 
a.	Remove the ‘Related Sequence No.’ Column from the LC M table
b.	Remove the text ‘(most recent last)’ from the Sequence No. column label in LCM table.
c.	Replace all the texts ‘Number’ with ‘No.’, for consistency.  Please look thru ALL the templates to replace ALL ‘Number’ with ‘No.’
d.	Shorten the Date Field label text in LCM table by removing the ‘(mmm-yy-dd)’ text
e.	Widen the Sequence Description column in the LCM table to allow for full data visibility
         i.	The text box object should be able to increase to 2 rows for users to see the full data
         ii.	The ‘mmmm-dd-yyyy’ values within specific sequence descriptions should appear as calendar icon, for user to select a data.
f.	‘Requestor of Solicited Information’:
         i.	The data field and label should be hidden, and only visible when user select ‘YES’ to question: Is this solicited information?
         ii.	The label should only be on one line (versus 2 lines currently)
@MartinBernard  @kpaschakis

**Comment by MartinBernard** [comment]
@vdilawri & @cqpham - thx for the update. If these as well as other tickets have been completed and validated. Pls close item.
