### ISSUE TITLE
2016-03-23 Additional REP wireframe updates

### ISSUE THREAD

**Issue by vdilawri** [hres/wireframes#12]
1.	RT Step 2:  The LCM table rule should be to have the most recent record as ‘first’ record.  Older records (rows) should fall beneath most recent.

2.	RT Step 2: Sequence Description values – some additional enhancements as follows; 

 a.	PSUR-C, PSUR-N, PSUR-PV – there are 2 date values for user input. Can a calendar object be added for each?
 b.	UDRA - For ‘unsolicited data’ can a text field be added for user input?
 c.	RMP-PV – for version number – can a user text field be added for user input (5 char. Max)?

3.	RT Step 2: Sequence description cascading lists: Visual display of lists

 a.	Can the list be ‘bound’ by the ‘middle’ of the lists, versus the ‘top’.  Or can this be displayed ‘automatically’ depending on whare list appears on screen

4.	RT Step 2:  ‘Is this solicited information’ label – can this be placed on one line also?

5.	RT Step 3: remove the label and check box titled “Same Official as uploaded Regulatory Activity (RA)”

6.	RA Step 2: Dossier ID field:  Add read-only text box with the value “HC6-24” within it

7.	RA Step 2: Reg. Activity Type dropdown list:  This list value should NOT be editable

@MartinBernard @kpaschakis @cqpham

**Comment by cqpham** [comment]
@ralphbolo

**Comment by MartinBernard** [comment]
@kpaschakis - can we close this?

**Comment by vdilawri** [comment]
Closed. All issues fixed.
@MartinBernard @kpaschakis @cqpham @ralphbolo
