### ISSUE TITLE
REP Wireframes - Web standards compliance - high level assessment

### ISSUE THREAD

**Issue by kpaschakis** [hres/wireframes#15]
[RDIMS_EAST-#409673-v1A-High_level_assessment_-_Regulatory_Enrolment_Process_.DOCX](https://github.com/hres/wireframes/files/219225/RDIMS_EAST-.409673-v1A-High_level_assessment_-_Regulatory_Enrolment_Process_.DOCX)
@cqpham 
As discussed, please action the items discussed in the following report:

**Comment by MartinBernard** [comment]
Pls make sure to action this one and close ticket by end of week when you leave.

**Comment by cqpham** [comment]
[RDIMS_EAST-#409673-v1A-High_level_assessment_-_Regulatory_Enrolment_Process_.DOCX](https://github.com/hres/wireframes/files/242921/RDIMS_EAST-.409673-v1A-High_level_assessment_-_Regulatory_Enrolment_Process_.DOCX)
@kpaschakis @MartinBernard 

Here's the updated document. I have finished most of the changes and added comments to the document.
