### ISSUE TITLE
2016-04-20 Additional REP tempate updates

### ISSUE THREAD

**Issue by vdilawri** [hres/wireframes#16]
1.	CO Step 2: ‘Same as Main Contact Information (From step 1a)” text
        a.	Please align this text with the ‘Company Representative Information’ title
        b.	Repeat above for all the Step 3 text as well

2.	DO Step 2: Pharmaceutical information tab
       a.	The question ‘Is this a non-prescription drug to which one or more Schedule A claims apply?’ [Yes/No
       i.	When Yes selected and the additional text appears, the last text box titled: “Please list the Schedule A claims….:
             1.	This text box should be 2 lines and when text exceeds, to have  scroll bar to show the whole text. […similar to RA Step 2 – ‘Reason for Filing…’]

3.	RA Step 2: ‘HC6-24-‘ label to be changed to ‘HC6-024-‘

4.	RT Step 2: Control ID text box
       a.	Need to expand to show all the 6 digits

5.	RT Step 2: Place the Company ID, Dossier Name, Dossier ID on one line to reduce space

6.	RT Step 2: Place the ‘Regulatory Activity Contact [for THIS Regulatory Activity]’ at the end / bottom of the page

7.	RT Step 2: When ‘ Is this an eCTD transaction?’ = NO
       a.	The lower Sequence Description fields should work the same as the ‘cascading list’ for sequence description within the LCM table

8.	RT Step 2: Only allow 1 sequence description to be added (…the LCM table will be visible only when previous RT file is loaded]

9.	RT Step 2: The Company ID, Dossier Name, Dossier ID – should be prefilled with data from Step 1 uploading (…is there a way to highlight this somehow?)

@kpaschakis @cqpham @ralphbolo @MartinBernard

**Comment by MartinBernard** [comment]
@cqpham - please make sure to action and close before you leave. If you've already completed this then close immediately.
