### ISSUE TITLE
Overall Status of REP Wire Frame

### ISSUE THREAD

**Issue by MartinBernard** [hres/wireframes#6]
@kpaschakis and @cqpham 

What's the overall status for completing this phase of the wire frame? 

The idea was to develop something that could be presentable to groups/ industry. 

I believe Chi has done a fantastic job so far but it's now been two weeks. Looking at the for now, in my view and for the sake of a wire frame, we're close to done.

Pls confirm.

**Comment by cqpham** [comment]
@MartinBernard and @kpaschakis 
I've finished most of the issues that needed to be fixed or changed except for the pick list values (which I'm still waiting for). There are a few more amendment and attestation html pages that need to be done, but it will not take me long. Once I've added those pages, I can start on working on some validation stuff (if that is something needs to be done).

**Comment by MartinBernard** [comment]
@cqpham  & @kpaschakis  

Thanks for the update. I would say finalize what you've indicated here but validation stuff is probably not necessary at this time for the wire frame

**Comment by MartinBernard** [comment]
Closing at this time.
